### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by ItsNoted** [vanillacode314/SimpleWildcardsComfyUI#1]
Hey there. Are there any usage instructions? How can I use it in the prompt? I tried using the standard ``__wildcard__`` call but it does not seem to be working? Do I have to add another node to the workspace? if so where can it be found?

**Comment by IckeBins67** [comment]
Better use https://github.com/bash-j/mikey_nodes including wildcard node. Tutorials also on YT.

**Comment by ItsNoted** [comment]
Thanks. I figured it out pretty quickly. Sorry for the late close!
